graph LR
    subgraph Nodes
        LS[LidarSimulator]\n(publishes distance) --> DT[distance topic (std_msgs/Float32)]
        OM[ObstacleMonitor]\n(subscribes distance, publishes alert) --> AL[alert topic (std_msgs/String)]
    end


LS --> DT
OM --> DT
OM --> AL